{
 "title": "promcord",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "guild", "label": "Guild", "query": { "query": "msg_count_total" } },
   { "name": "user", "label": "User", "query": { "query": "msg_count_total" } },
   { "name": "game", "label": "Game", "query": { "query": "game_usage" } }
  ]
 },
 "panels": [
  {
   "title": "Discord Gateway Ping",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "discord_ping_websocket" }
   ]
  },
  {
   "title": "Total Messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(msg_count_total{guild=~\"$guild\"}) by (guild)",
     "legendFormat": "Messagecount {{guild}}"
    }
   ]
  },
  {
   "title": "Server Boost Status",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "booster_count{guild=~\"$guild\"}",
     "legendFormat": "Server Boost Count"
    }
   ]
  },
  {
   "title": "Total Members",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(member_count{guild=~\"$guild\"})"
    }
   ]
  },
  {
   "title": "Message Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(msg_count_total{guild=~\"$guild\"}[1m])) by (guild)",
     "legendFormat": "Messageactivity {{guild}}"
    }
   ]
  },
  {
   "title": "Humans",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(member_count{guild=~\"$guild\"} ) - sum(bot_count{guild=~\"$guild\"} ) "
    }
   ]
  },
  {
   "title": "Bots",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bot_count{guild=~\"$guild\"})"
    }
   ]
  },
  {
   "title": "Voice Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(voice_time{guild=~\"$guild\"})"
    }
   ]
  },
  {
   "title": "Messages by Top 25 User",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(25, sum(msg_count_total{user=~\"$user\",guild=~\"$guild\"})by(user))",
     "legendFormat": "User {{user}}"
    }
   ]
  },
  {
   "title": "Online Members",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(member_online{guild=~\"$guild\"})"
    }
   ]
  },
  {
   "title": "Active Users (1d)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(changes(msg_count_total{user=~\"$user\",guild=~\"$guild\"}[1d]) > 0) by (user))"
    }
   ]
  },
  {
   "title": "Active Users (1w)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(changes(msg_count_total{user=~\"$user\",guild=~\"$guild\"}[1w]) > 0) by (user))"
    }
   ]
  }
 ]
}